### ISSUE TITLE
Create New Task - Filter Images by datetime

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/scout#60]
## Context
Users have discovered that there is a need for separating flight by the time of the flight, as well as the date

## User Story
As a lab lead creating new tasks, I am able to leverage a datetime filter that works off the image exif
- Page impacted: `main/views/pages/tasks-new.ejs`
- update 'startDate' and 'endDate' components to be some form of datetime input

## Technical Notes
Recommended to use `bootstrap-datetimepicker.js` (will need to use `moment.js` to get it working)

## QA verification
1. upload a series of images with known sequential datetime exif
1. navigate to create new task: select images modal

- [ ] start time is a datetime field
- [ ] end time is a datetime field
- [ ] filter respects datetime exif

**Comment by erinz2020** [comment]
after quite a few researches and experiments, it turns out that Bootstrap DateTimePicker(designed for bootstrap 3) does not work properly with bootstrap 5 which we are currently using. I found some workarounds(update this manually<input type="datetime-local">) and now it is working on chrome, however firefox does not support picking time with that, but we can still input time manually

chrome:
![image](https://github.com/user-attachments/assets/84a0da2d-e6fd-4bf2-9abf-7e07ff558a7c)

Firefox:
![image](https://github.com/user-attachments/assets/001b3ee6-8916-446a-b3ee-f410832a7c0a)

**Comment by erinz2020** [comment]
it turns out that native html datetime picker does not work well with firefox. selecting a datetime won't trigger onchange functions, so turning to other libraries. @TanyaStere42

**Comment by erinz2020** [comment]
flatpickr seems to be the solution
